### ISSUE TITLE
Cursor sync is broken

### ISSUE THREAD

**Issue by benbro** [goinstant/rich-text-editor#22]
To reproduce:
1. open the demo with two browsers.
https://developers.goinstant.com/v1/widgets/rich_text_editor.html
2. Clear the page and enter some text with browser 1.
3. With browser 2, place the cursor in the middle of the text and start typing.
The cursor will jump to a different place.

**Comment by benbro** [comment]
Does the demo include this fix?
I still see cursor sync issues there.

**Comment by jhchen** [comment]
It has not been deployed yet. We are fixing a couple other bugs on Quill itself and will deploy once those are fixed and fixes added to this repo. I'll update here when that happens. Thank you for the bug reports.

**Comment by jhchen** [comment]
The fix has been deployed! Thank you for your patience.

**Comment by benbro** [comment]
Thanks
