### ISSUE TITLE
Lodash not being required in rich_text_editor.js

### ISSUE THREAD

**Issue by colinmacdonald** [goinstant/rich-text-editor#5]
https://github.com/goinstant/rich-text-editor/blob/master/lib/rich_text_editor.js#L10

This module is using lodash but is not requiring it. The example only works because lodash is on the window.

**Comment by jhchen** [comment]
Fixed in https://github.com/goinstant/rich-text-editor/commit/daa045de1193898f4e9720644b3af960d4801fd1
